language: node_js
branches:
  only:
    - master
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - node --version | grep -q 'v0.8' && npm install -g npm@2 || true
node_js:
  - "5.3"
script: npm run build
